name: datacleaningworkflow
on: workflow_dispatch

jobs:
        data_pipeline:
                name: datacleaning_pipeline
                runs-on: self-hosted
       
                steps:
                - name: setup python
                  uses: actions/setup-python@v4
                  with:
                    python-version: "3.6"

                - name: checkout code
                  uses: actions/checkout@v4

                - name: install dependencies
                  run: |
                    pwd
                    cd ModelFiles
                    pip install -r requirements.txt

                - name: clean_data
                  run: |
                    pwd
                    ls -al
                    pwd
                    cd ModelFiles
                    python datacleaning.py
