name: datacleaningworkflow
on: workflow_dispatch

jobs:
        data_pipeline:
                name: datacleaning_pipeline
                runs-on: ubuntu-latest
       
                steps:
                - name: setup python
                  uses: actions/setup-python@v4
                  with:
                    python-version: "3.10"

                - name: checkout code
                  uses: actions/checkout@v4

                - name: install dependencies
                  run: |
                    pwd
                    cd ModelFiles
                    python -m pip install --upgrade pip
                    python -m pip install -r requirements.txt

                - name: clean_data
                  run: |
                    pwd
                    ls -al
                    pwd
                    cd ModelFiles
                    python datacleaning.py

                #- name: uploading cleaned data artifact
                 # uses: actions/upload-artifact@v4
                  #with:
                   # name: cleaned-data
                    #path: ModelFiles/cleaned_data.csv


                - name: Commit cleaned data back to repo
                  run: |
                    git config --global user.name "github-actions[bot]"
                    git config --global user.email "github-actions[bot]@users.noreply.github.com"
                    git add ModelFiles/cleaned_data.csv
                    git commit -m "Add/update cleaned_data.csv from datacleaningworkflow" || echo "Nothing to commit"
                    git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
                  env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

