name: modeltrainingworkflow

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run unit tests for datacleaning"]
    types:
      - completed

jobs:
        training_eval:
                if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }} # on manual triggerr or only if previous workflow was successful
                name: modeltraining_pipeline
                runs-on: ubuntu-latest
       
                steps:
                - name: setup python
                  uses: actions/setup-python@v4
                  with:
                    python-version: "3.10"

                - name: checkout code
                  uses: actions/checkout@v4

                - name: install dependencies
                  run: |
                    pwd
                    cd ModelFiles
                    pip install -r requirements.txt

                - name: train_model
                  run: |
                    pwd
                    ls -al
                    pwd
                    cd ModelFiles
                    python training_eval.py

                - name: Commit pickle file back to repo
                  run: |
                    git config --global user.name "github-actions[bot]"
                    git config --global user.email "github-actions[bot]@users.noreply.github.com"
                    git add ModelFiles/HousingModel.pkl
                    git commit -m "Add/update HousingModel.pkl from modeltrainingworkflow" || echo "Nothing to commit"
                    git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
                  env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

