name: Unit Test for DataCleaning

on:
  workflow_dispatch:
  push:
    branches:
      - dev-main
    paths:
      - 'ModelFiles/datacleaning.py'
      - 'ModelFiles/originaldata.csv'
      - 'ModelFiles/training_eval.py'
      - 'ModelFiles/flaskApp.py'
      - 'ModelFiles/Dockerfile'
      - 'ModelFiles/requirements.txt'

jobs:
  run-unit-test-on-datacleaning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List project structure
        run: ls -R

      - name: Install dependencies
        run: |
          cd ModelFiles
          pip install -r requirements.txt

      - name: Run pytest on datacleaning unit tests
        run: |
          cd ModelFiles
          pytest test_datacleaning.py --maxfail=1 --disable-warnings -v
