name: Run unit tests for datacleaning

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["datacleaningworkflow"]
    types:
      - completed

jobs:
  run-unit-tests:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }} # on manual triggerr or only if previous workflow was successful
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List project structure
        run: ls -R

      - name: Install dependencies
        run: |
          cd ModelFiles
          pip install -r requirements.txt

      - name: Run pytest on datacleaning unit tests
        run: |
          cd ModelFiles
          pytest test_datacleaning.py --maxfail=1 --disable-warnings -v
